name: z1regfus
channels:
  - defaults
dependencies:
  - ipython
  - h5py
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - dask
  - distributed
  - bokeh
  - bcolz
  - pip
  - pip:
    - simpleitk
    - redis
    - redis_lock
    - dipy
    - scikit-image
    - transformations
    - czifile==2019.1.26