name: z1regfus_windows
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - ipython
  - h5py
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - dask
  - distributed
  - bokeh
  - bcolz
  - scikit-image
  - tifffile
  - pip
  - pip:
    - simpleitk # replace by simpleelastix
#    - czifile==2019.1.26