name: mvregfus
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - ipython
  - h5py
  - h5pickle
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - dask
  - distributed
  - bokeh
  - bcolz
  - scikit-image
  - tifffile
  - dipy
  - pip
  - pip:
      - SimpleITK
#  - pip:
#    - simpleitk # replace by simpleelastix
#    - czifile==2019.1.26