name: z1regfus
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - ipython
  - h5py
  - numpy
  - scipy
  - sparse
  - scikit-learn
  - pandas
  - dask=1.2.2
  - distributed
  - bokeh
  - bcolz
  - scikit-image
  - tifffile
  - dipy
  - pip
#  - pip:
#    - simpleitk # replace by simpleelastix
#    - czifile==2019.1.26